### ISSUE TITLE
How to add caps?

### ISSUE THREAD

**Issue by hiteshjoshi** [notedit/gst#10]
I couldnt find any examples of adding caps.

I wish to do something like this

gst-launch-1.0 appsrc name=src ! application/x-rtp, payload=96, encoding-name=OPUS ! rtpopusdepay ! decodebin ! appsink name=sink

How do I add `application/x-rtp, payload=96, encoding-name=OPUS` to dynamic pipelines?

**Comment by notedit** [comment]
https://github.com/notedit/gst/blob/4c7acc1ad4f876f277e42bea9fd342f34baab0e0/gst_test.go#L64

**Comment by hiteshjoshi** [comment]
Tried it. It doesn’t add caps as a new process. 
It tries to add caps to available elements with caps property which is right. 
But how do I go caps in this direction 

somesrc ! Caps string ! process  ! sink 

The said elements adds it like 

somesrc caps=“caps” ! process ! sink

**Comment by hiteshjoshi** [comment]
Also while we are at it. Can you also suggest about named variables ?

Like how do I use “mix “ as named variable in dynamic pipeline?

Sorry I am just beginning to get into gstreamer. This is my second day.
