### ISSUE TITLE
How to send Events (e.g. End-Of-Stream) down the Pipeline?

### ISSUE THREAD

**Issue by jackfreed** [notedit/gst#11]
In python it would be something like:

`pipeline.send_event(Gst.Event.new_eos())`

i am trying to use it from an appsrc and found this
https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/blob/1.16.2/gst-libs/gst/app/gstappsrc.c

```
 * When the application has finished pushing data into appsrc, it should call
 * gst_app_src_end_of_stream() or emit the end-of-stream action signal. After
 * this call, no more buffers can be pushed into appsrc until a flushing seek
 * occurs or the state of the appsrc has gone through READY.
```

@notedit any help is highly appreciated

**Comment by nibbleshift** [comment]
Have you already solved this?

**Comment by nibbleshift** [comment]
I am working on a PR for this, see here: https://github.com/nibbleshift/gst/commit/dc6e07354237fb4ced34635fbee4fcc88af252e3

**Comment by notedit** [comment]
@nibbleshift Thanks

https://github.com/notedit/gst/releases/tag/v0.0.6
