### ISSUE TITLE
Add support for gst_pad_add_probe

### ISSUE THREAD

**Issue by nibbleshift** [notedit/gst#18]
Add support for adding probe's to pads.

**Comment by nibbleshift** [comment]
I am currently working on a PR to add support for gst_pad_add_probe.

It will work something like this.
```
pad.AddProbe(PadProbeTypeIdle, func(pad *Pad, info *PadProbeInfo) (PadProbeReturn) {
    fmt.Println("Called")
})
```

I am having one issue with the PR so far:

./pad.go:134:141: cannot convert callback (type PadProbeCallback) to type _Ctype_GstPadProbeCallback

See here: https://github.com/nibbleshift/gst/blob/master/pad.go#L134


I am still working through how to properly cast that struct.

**Comment by vahid-sohrabloo** [comment]
Added and merged https://github.com/notedit/gst/pull/19
